version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: writing-assistant-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123  # root用户密码
      MYSQL_DATABASE: writing-assistant-db  # 数据库名称
      MYSQL_USER: writer  # 创建新用户
      MYSQL_PASSWORD: writer123  # 新用户密码
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

volumes:
  mysql_data:
