#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

cd frontend && {
  echo "Running incremental type check..."
  tsc --noEmit --incremental || exit 1
  
  echo "Running lint-staged..."
  npx lint-staged
}
